// Multi-Target and the two rulings that hang off it (FAQ B7, A25/D11).
//
//   B7: "all attacks made as part of a Multi-Target action are resolved
//   simultaneously. The Smoke Screens generated by Emergency Smoke are placed
//   only after all attacks have been fully resolved." So the ordering is the
//   ruling, and what is testable without a DOM is the three derivations the
//   ordering is built on: who has Multi-Target and for how many, who reacts to
//   being shot at, and who Designates dice.
import { readFileSync, writeFileSync } from 'node:fs';

const unitsSrc = readFileSync(new URL('../src/units.ts', import.meta.url), 'utf8');
const cut = (from, to, what) => {
  const a = unitsSrc.indexOf(from);
  const b = unitsSrc.indexOf(to, a);
  if (a < 0 || b < 0 || b <= a) throw new Error('could not locate ' + what);
  return unitsSrc.slice(a, b);
};
const tmp = new URL('./_multitarget.slice.ts', import.meta.url);
writeFileSync(
  tmp,
  'type Card = any;\ntype CardAction = any;\ntype GameData = any;\ntype Token = any;\ntype PartSlot = any;\n'
    + 'const PART_SLOTS = ["torso","chasis","leftHand","rightHand","backpack"];\n'
    + cut('export function tokenCards', '// ---------- Tarantula Loads', 'tokenCards')
    // One slice for all three: they sit together in source and the end marker
    // is the next unrelated export, so a reorder fails loudly instead of
    // silently dropping one of them.
    + cut('// ---------- Multi-Target', '// Every card id currently on the board', 'the Multi-Target block'),
);
const { multiTargetLimit, attackReactionsOf, designationsOn } = await import(tmp.href);

const raw = JSON.parse(readFileSync(new URL('../../data/cards.json', import.meta.url), 'utf8'));
const cards = Array.isArray(raw) ? raw : raw.cards ?? [];
const byId = new Map(cards.map((c) => [String(c.id), c]));
const data = { byId };

let pass = 0, fail = 0;
const check = (name, got, want) => {
  const g = JSON.stringify(got), w = JSON.stringify(want);
  if (g === w) { pass++; console.log(`  ok   ${name}`); }
  else { fail++; console.log(`  FAIL ${name}\n       want ${w}, got ${g}`); }
};
const actionOf = (id, name) => (byId.get(id)?.actions ?? []).find((a) => (a.name?.en ?? a.name?.zh ?? a.id) === name || a.id === name);

console.log('Multi-Target, its ordering and Designate — FAQ B7/A25\n');

// ---------- who has it, and for how many ----------

// The inline keyword is the literal string 多目标X — an X, never a digit — so a
// reader that trusted the keyword alone would get a limit of NaN on every card.
const crisis2 = actionOf('547', 'Full-auto');
check('the H2-B Crisis II Full-auto is Multi-Target 5',
  multiTargetLimit(crisis2), { limit: 5, condition: null });
check('and the keyword really does carry no number',
  (crisis2.keywords ?? []).map((k) => k.inline), ['多目标X']);

// 546 is the Chinese-only H2-A: no English text at all, so it proves the
// structured gameRules path rather than the prose fallback.
check('the Chinese-only H2-A gets the same limit off its gameRules',
  multiTargetLimit(actionOf('546', '546_A')), { limit: 5, condition: null });

// The two conditional grants. Neither condition is tracked by the app, so the
// limit is offered WITH the condition named rather than applied silently or
// dropped silently.
const stratus = multiTargetLimit(actionOf('038', 'Full-auto'));
check('the Stratus HMG gains Multi-Target 3 only Two-Handed', [stratus.limit, /Two-Handed/.test(stratus.condition)], [3, true]);
const lmg = multiTargetLimit(actionOf('556', 'Full-auto'));
check('the R7MG LMG gains it only Charged', [lmg.limit, /Charged/.test(lmg.condition)], [3, true]);
// Charged is an either/or on that card, and losing the alternative silently
// would be the sort of thing a player never notices.
check('and the Charged note says Suppression is the other arm', /Suppression/.test(lmg.condition), true);

// Nothing else in the box has it, so a fifth card appearing gets noticed.
const withMulti = cards.filter((c) => (c.actions ?? []).some((a) => multiTargetLimit(a)));
check('exactly four cards carry Multi-Target', withMulti.map((c) => String(c.id)).sort(), ['038', '546', '547', '556']);

// An ordinary Firing action must not be dragged in by the word "target".
check('a plain rifle has no Multi-Target', multiTargetLimit((byId.get('025')?.actions ?? [])[0]), undefined);

// The prose fallback, for a card added later without gameRules.
check('the printed line alone is enough',
  multiTargetLimit({ description: { en: '· Multi-Target 4.' } }), { limit: 4, condition: null });
check('and a conditional printed line keeps its condition',
  multiTargetLimit({ description: { en: '· [Two-Handed] Gains Multi-Target 2.' } })?.limit, 2);
// The condition is read off the LINE the match sits on, not the whole card, or
// a [Two-Handed] clause about something else would poison an unconditional grant.
check('a Two-Handed clause on another line does not attach itself',
  multiTargetLimit({ description: { en: '· [Two-Handed] Range +2 grids.\n· Multi-Target 3.' } }),
  { limit: 3, condition: null });

// ---------- the reaction B7 is about ----------

const mech = (torso, over = {}) => ({
  uid: 1, side: 's1', kind: 'mech', cardId: torso, col: 3, row: 3, size: 3, facing: 0,
  mech: { torso }, partStates: { torso: 'intact' }, ammo: {}, statuses: [], ...over,
});

// The H2-A carries Multi-Target 5 AND Emergency Smoke on the same torso, which
// is what makes B7's question reachable at all in this box.
check('the H2-A reacts to being shot at with 2 Smoke Screens',
  attackReactionsOf(data, mech('546')).map((r) => [r.name, r.smoke.count, r.smoke.range, r.afterDestroyed]),
  [['应急烟幕', 2, 1, true]]);
// FAQ D10 asks whether a Reaper destroyed outright still gets its Emergency
// Smoke and answers yes; the card encodes it as usableAfterDestroyed, so a dead
// Part is no bar HERE and would be on a card without the flag.
check('and still reacts with the Part destroyed (FAQ D10)',
  attackReactionsOf(data, mech('546', { partStates: { torso: 'destroyed' } })).length, 1);
check('a Mech with no such card reacts to nothing', attackReactionsOf(data, mech('547')), []);
// The card prints storage 1, so syncMagazines tracks its uses as Ammo and a
// spent Emergency Smoke must stop being offered — untracked ammo never gates.
check('a spent Emergency Smoke is not offered again',
  attackReactionsOf(data, mech('546', { ammo: { '546_B': 0 } })), []);
check('but one use left still offers',
  attackReactionsOf(data, mech('546', { ammo: { '546_B': 1 } })).length, 1);

// ---------- Designate (A25/D11) ----------

check('the Volcano core Designates 1 White die',
  designationsOn(data, mech('016')).map((d) => [d.name, d.color, d.count]),
  [['Armor Countermeasures', 'white', 1]]);
// A destroyed Part grants nothing — unlike the reaction above, this card claims
// no exemption.
check('a destroyed Volcano core Designates nothing',
  designationsOn(data, mech('016', { partStates: { torso: 'destroyed' } })), []);
check('an ordinary core Designates nothing', designationsOn(data, mech('547')), []);
// All three Volcano variants, and only those three.
const designators = cards.filter((c) => (c.actions ?? []).some((a) =>
  (a.gameRules ?? []).some((g) => (g.effects ?? []).some((e) => e.type === 'designate_dice_result'))));
check('exactly three cards Designate dice', designators.map((c) => String(c.id)).sort(), ['016', '246', '280']);

console.log(`\n${pass} passed, ${fail} failed`);
process.exitCode = fail ? 1 : 0;
